title: Shane's Slides
description: Open Source Community And Trademark Slides
author:
  name: Shane Curcuru
  twitter: shanecurcuru

theme: retlab
repository: ShaneCurcuru/slides
logo: "/assets/img/headshot.jpg"

# TODO Leave slide decks alone
exclude: 

timezone: America/New_York
encoding: UTF-8
lang: en-US
branch: master
ga_username: UA-77233462-3

# Pages to include in header navigation
nav_pages:
  - index.html
  - about.md
  - contact.md

# Disqus login information, for comments
disqus:
  shortname: shanecurcuru

social:
  name: Shane Curcuru
  links:
    - https://twitter.com/ShaneCurcuru
    - https://www.linkedin.com/in/ShaneCurcuru
    - https://plus.google.com/+ShaneCurcuru
    - https://github.com/ShaneCurcuru
    
# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/ShaneCurcuru
    icon: twitter
  - name: GitHub
    url: https://github.com/ShaneCurcuru
    icon: github
  - name: LinkedIn
    url: https://www.linkedin.com/in/ShaneCurcuru
    icon: linkedin
  - name: Google
    url: https://plus.google.com/+shanecurcuru
    icon: google-plus
  - name: Keybase
    url: https://keybase.io/shanecurcuru
    icon: key

# Front matter defaults
permalink: "/:year/:month/:title/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

# Plugins
gems:
  - jemoji
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap